mex -IC:\opencv\opencv\build\include ...
    -IC:\opencv\opencv\build\include\opencv ...
    -LC:\opencv\opencv\build\x64\vc10\lib ...  
    cyStereoRectify.cpp cy_cvmex.cpp -lopencv_imgproc240  -lopencv_core240 -lopencv_highgui240...
    -lopencv_calib3d240 -lopencv_contrib240;